project:
  type: website
  output-dir: docs

website:
  title: "INLA Tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false